[package]
name = "aeterna"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = { version = "2.7.0", features = ["https"] }
soup = "0.5.1"
